# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    # - os: linux
  fast_finish: true
notifications:
  email: false
services:
  - xvfb
before_install:
  - wget http://home.zcu.cz/~mjirik/lisa/install/install_conda.sh && source install_conda.sh
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #     wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  #   elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
  #     wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -O miniconda.exe;
  #   fi
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - export PATH="$HOME/miniconda/bin:$PATH"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
    # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create --yes -n travis -c mjirik -c conda-forge python=3 io3d
  - source activate travis
  - which julia
  - julia -e 'VERSION'
  # - conda list
  - python -m io3d.datasets -l 3Dircadb1.1 jatra_5mm nrn4
  - conda install --yes -c conda-forge pip numpy PyOpenGL
  # Install PyPlasm
  # There is no pypi wheel for linux we have to build
      # pip3 install setuptools PyOpenGL PyOpenGL-accelerate  numpy ;
      # pip install PyOpenGL PyOpenGL-accelerate  numpy ;
  - conda install --yes pip
  # - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
  #     sudo apt-get install python3 python3-dev libasound2-dev libfreetype6-dev xorg-dev libglu1-mesa-dev python3-pip libldap2-dev ;
  #     sudo apt-get install juce-modules-source ;
  #     pip install PyOpenGL ;
  #     git clone git://github.com/plasm-language/pyplasm.git ;
  #     cd pyplasm ;
  #     mkdir build && cd build ;
  #     cmake .. ;
  #     cmake --build . --config Release -- -j 8 ;
  #     cmake --build . --config Release --target install ;
  #     cd .. ;
  #   fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip install pyplasm ; echo "plasm installed ----" ; fi
  - conda list
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/cvdlab/LinearAlgebraicRepresentation.jl", rev="julia-1.0"))'
  - julia -e 'using Pkg; Pkg.add("PyCall"); ENV["PYTHON"] = split(read(`which python`, String), "\n")[1]; Pkg.build("PyCall")'
  - julia -e 'using PyCall; println(PyCall.PYTHONHOME)'
  # - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/cvdlab/Plasm.jl", rev="julia-1.0"))'
  # - julia -e 'using Pkg; Pkg.add("Plasm")'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/mjirik/ExSu.jl"))'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/mjirik/Io3d.jl"))'
  # - julia -e "using Pkg; Pkg.add('https://github.com/mjirik/ExSu.jl')"
  - pwd
  # we do not need Plasm anymore
  # - julia -e 'using Plasm'
  - julia -e 'using LinearAlgebraicRepresentation'


  # Install LarSurf dependencies
  - conda install -c conda-forge pandas
  - julia -e 'using Pkg; Pkg.add("Revise")'
  - julia -e 'using Pkg; Pkg.add("JLD2")'
  - julia -e 'using Pkg; Pkg.add("FileIO")'
  - julia -e 'using Pkg; Pkg.add("Pandas")'
before_script:
    # GUI
    - "export DISPLAY=:99.0"
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
