name = "LarSurf"
uuid = "39bcc72a-2642-51fe-8404-ebe33c8ec443"
authors = ["Miroslav Jirik <miroslav.jirik@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
